### PR TITLE
Add latex install

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR adds a command to install Latex to the CS server. @hdoupe I believe that this should resolve our issues with CS and the reports. I've tried testing in the Docker container you set up for me, but the tests kept getting killed for some reason. But the added command does successfully install `pdflatex` which is what the tests on compute studio are currently saying is missing.

### CODE REVIEW

**Comment by hdoupe** [comment]
@andersonfrailey Nice, this sounds like progress! 

It could be that the tests are running out of memory. The code running in the container may not be writing to disk like it would if you were running it directly... I can try it on my desktop to verify if this is what's going on.

**Comment by andersonfrailey** [comment]
@hdoupe good point about the memory! I'll bump up the amount I let docker use and try again later

**Comment by hdoupe** [comment]
Hey @andersonfrailey have you had any luck running #142?

**Comment by andersonfrailey** [comment]
@hdoupe haven't had a chance to yet. I'll try and get it going this weekend

**Pull request merged**
