### PR TITLE
Add header for pc_aftertaxinc

### LINKED ISSUE #102: Differences table shows "pc_aftertaxinc"
Other column headers are written out phrases.
image

### PR DESCRIPTION
**Pull request by MaxGhenis**
Fixes #102

### CODE REVIEW

**Comment by hdoupe** [comment]
@MaxGhenis thank you for opening this PR! It tooks some digging, several print statements, and a strategic placement of `breakpoint()` but I figured out that the row names are actually defined in this line of code:

https://github.com/PSLmodels/Tax-Brain/blob/2c83610a8969ca1af8eaa1af3eb8281beaa4b086/cs-config/cs_config/helpers.py#L375-L376

Dropping the `-2` uses the full list that's defined in `taxcalc.utils` and fixes the column name. The change you made caused a failure in this test:
```
taxbrain/tests/test_report.py::test_report FAILED                                                                                             [100%]

===================================================================== FAILURES ======================================================================
____________________________________________________________________ test_report ____________________________________________________________________

self = Index(['c00100', 's006', 'iitax', 'ubi', 'refund', 'benefit_value_total',
       'aftertax_income', 'c04800', 'otherta...ed_income', 'c62100',
       'standard', 'c07100', 'payrolltax', 'combined', 'c04600', 'c04470'],
      dtype='object')
key = 'pc_aftertaxinc', method = None, tolerance = None

    @Appender(_index_shared_docs["get_loc"])
    def get_loc(self, key, method=None, tolerance=None):
        if method is None:
            if tolerance is not None:
                raise ValueError(
                    "tolerance argument only valid if using pad, "
                    "backfill or nearest lookups"
                )
            try:
>               return self._engine.get_loc(key)

../../miniconda3/envs/taxbrain-dev/lib/python3.7/site-packages/pandas/core/indexes/base.py:2897: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???

pandas/_libs/index.pyx:107: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???

pandas/_libs/index.pyx:131: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???

pandas/_libs/hashtable_class_helper.pxi:1607: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   KeyError: 'pc_aftertaxinc'

pandas/_libs/hashtable_class_helper.pxi:1614: KeyError

During handling of the above exception, another exception occurred:

tb_static = <taxbrain.taxbrain.TaxBrain object at 0x7f5c7e8455c0>

    def test_report(tb_static):
        """
        Ensure that all report files are created
        """
        outdir = "testreform"
        name = "Test Report"
        report(
>           tb_static, name=name, outdir=outdir
        )

taxbrain/tests/test_report.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
taxbrain/report.py:170: in report
    text_args["notable_changes"] = notable_changes(tb, change_threshold)
taxbrain/report_utils.py:342: in notable_changes
    totals = tb.weighted_totals(var).transpose()
taxbrain/taxbrain.py:142: in weighted_totals
    self.base_data[year][var]).sum()
../../miniconda3/envs/taxbrain-dev/lib/python3.7/site-packages/pandas/core/frame.py:2995: in __getitem__
    indexer = self.columns.get_loc(key)
../../miniconda3/envs/taxbrain-dev/lib/python3.7/site-packages/pandas/core/indexes/base.py:2899: in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
pandas/_libs/index.pyx:107: in pandas._libs.index.IndexEngine.get_loc
    ???
pandas/_libs/index.pyx:131: in pandas._libs.index.IndexEngine.get_loc
    ???
pandas/_libs/hashtable_class_helper.pxi:1607: in pandas._libs.hashtable.PyObjectHashTable.get_item
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   KeyError: 'pc_aftertaxinc'

pandas/_libs/hashtable_class_helper.pxi:1614: KeyError
```

**Comment by MaxGhenis** [comment]
Thanks @hdoupe, I removed the initial change and instead removed the `[:2]` where you noted it, and I'm not getting the error you described above. However, I am getting this one:
```
 >       assert diff_png.exists() or diff_svg.exists()                                                    
E       AssertionError: assert (False or False)   
E        +  where False = <bound method Path.exists of PosixPath('testreform/difference_graph.png')>()                               
E        +    where <bound method Path.exists of PosixPath('testreform/difference_graph.png')> = PosixPath('testreform/difference_gr$
ph.png').exists                 
E        +  and   False = <bound method Path.exists of PosixPath('testreform/difference_graph.svg')>()                              
E        +    where <bound method Path.exists of PosixPath('testreform/difference_graph.svg')> = PosixPath('testreform/difference_gr$
ph.svg').exists                                 

taxbrain/tests/test_report.py:22: AssertionError
------------------------------------------------------- Captured stderr call --------------------------------------------------------
WARNING:bokeh.io.export:No SVG Plots were found.
WARNING:bokeh.io.export:No SVG Plots were found.
--------------------------------------------------------- Captured log call ---------------------------------------------------------
ERROR    weasyprint:images.py:231 Failed to load image at "file:///home/mghenis/Tax-Brain/testreform/difference_graph.svg" (URLError:
 <urlopen error [Errno 2] No such file or directory: '/home/mghenis/Tax-Brain/testreform/difference_graph.svg'>)
ERROR    weasyprint:images.py:231 Failed to load image at "file:///home/mghenis/Tax-Brain/testreform/dist_graph.svg" (URLError: <urlo
pen error [Errno 2] No such file or directory: '/home/mghenis/Tax-Brain/testreform/dist_graph.svg'>)
```
Thoughts?

For posterity: the labels are inherited from taxcalc in [taxcalc/utils.py#L118](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/utils.py#L118).

**Comment by hdoupe** [comment]
@MaxGhenis I was able to reproduce the error (CI would make this much easier!). I'm able to reproduce this error on the master branch by deleting an untracked directory at `Tax-Brain/testreform`. Let's merge this PR and tackle the test failure in a separate PR.

**Comment by hdoupe** [comment]
Thanks for the PR @MaxGhenis! I'll push these changes to C/S as soon as we get a new Tax-Brain release out.

**Pull request merged**
