### PR TITLE
Updates for recent releases of Bokeh and Tax-Calculator

### PR DESCRIPTION
**Pull request by Peter-Metz**
Make changes to code and tests to bring Tax-Brain up to date with Bokeh 2.0.0 and Tax-Calculator 2.9.0.

@hdoupe do we need to do anything to bump the last budget year to 2030? Seems like we're getting the year from Tax-Calc, which makes me think we might be good.

```python
class TaxBrain:

    FIRST_BUDGET_YEAR = tc.Policy.JSON_START_YEAR
    LAST_BUDGET_YEAR = tc.Policy.LAST_BUDGET_YEAR
```

Anything else I'm missing on the C/S side?

cc @andersonfrailey

### CODE REVIEW

**Comment by Peter-Metz** [comment]
The only test that is still failing locally is in `test_report.py` and seems to be unrelated to this PR or the Tax-Brain web app

**Comment by hdoupe** [comment]
@Peter-Metz I think you just need to update the years here: https://github.com/PSLmodels/Tax-Brain/blob/master/cs-config/cs_config/helpers.py#L58-L60

**Comment by Peter-Metz** [comment]
Thanks @hdoupe. Once this is merged, we'll have to issue a new release, right?

**Comment by hdoupe** [comment]
> Thanks @hdoupe. Once this is merged, we'll have to issue a new release, right?

Yep.

**Comment by hdoupe** [comment]
@Peter-Metz I hit an error when testing this locally. I just opened a PR on your branch with the fix: https://github.com/Peter-Metz/Tax-Brain/pull/1

**Comment by Peter-Metz** [comment]
Thanks @hdoupe for that PR. Good to merge on your end?

**Comment by hdoupe** [comment]
> Thanks @hdoupe for that PR. Good to merge on your end?

Yep, tests pass locally!

**Comment by hdoupe** [comment]
@Peter-Metz I think I have a solution for the bokeh problem. I'll have that up in about half an hour.

**Comment by hdoupe** [comment]
@Peter-Metz The fix is live. We don't need the `bokeh<2.0.0` pin anymore.

**Comment by hdoupe** [comment]
Tests passing for you locally @Peter-Metz ?

**Comment by Peter-Metz** [comment]
yessir @hdoupe

**Pull request merged**
