### PR TITLE
update API docs

### PR DESCRIPTION
**Pull request by jdebacker**
This PR fixes issue where the API sections are listed twice in the Jupyter Book (see the left sidebar [here](http://taxbrain.pslmodels.org/content/api/public_api.html)).  This was a result of some changes in the more recent JB releases.

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Now that #181 is merged, these test failures should go away when you merge this with the master branch.

**Comment by jdebacker** [comment]
@andersonfrailey Can you try rerunning the checks here?  It looks like there was just a timeout when installing some packages.

**Comment by andersonfrailey** [comment]
Thanks for working on this, @jdebacker! Anything else you want to add before I merge?

**Comment by jdebacker** [comment]
Nope - this is ready - thanks!

**Pull request merged**
