### PR TITLE
Filter unsectioned Tax-Calc params from C/S

### PR DESCRIPTION
**Pull request by Peter-Metz**
Following discussion in Tax-Calc [#2374](https://github.com/PSLmodels/Tax-Calculator/issues/2374), this PR filters out the unsectioned Tax-Calculator parameters in the Tax-Brain web app

cc: @andersonfrailey @hdoupe

### CODE REVIEW

**Comment by Peter-Metz** [comment]
As an FYI, some of the tests are failing because of (I believe) issues unrelated to this PR. I'm happy to close this PR for now or just hold off on merging until we sort the tests out.

**Comment by hdoupe** [comment]
@Peter-Metz #89 looks good. Do the tests pass locally with the updated environment in PR #91?

**Comment by Peter-Metz** [comment]
@hdoupe yep, the tests are passing locally with the exception of `test_report` (unrelated to this PR -- it's not properly exporting the png file). I'll poke around and try to get that test passing and open a separate PR. I think this one is good to be merged.

**Comment by hdoupe** [comment]
Cool, thanks @Peter-Metz!

**Pull request merged**
