### PR TITLE
Read updated puf file name from s3 bucket for cs usage

### LINKED ISSUE #183: C/S Build error
I'm getting this error when I try to deploy a new version of Tax-Brain.

I'll try again with the newest version of the PUF and will report back.

```
>       result = self.run_model(mp_spec, self.ok_adjustment)

/opt/conda/lib/python3.8/site-packages/cs_kit/validate.py:221: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cs-config/cs_config/functions.py:150: in run_model
    results = compute(*delayed_list)
/opt/conda/lib/python3.8/site-packages/dask/base.py:568: in compute
    results = schedule(dsk, keys, **kwargs)
/opt/conda/lib/python3.8/site-packages/dask/threaded.py:79: in get
    results = get_async(
/opt/conda/lib/python3.8/site-packages/dask/local.py:517: in get_async
    raise_exception(exc, tb)
/opt/conda/lib/python3.8/site-packages/dask/local.py:325: in reraise
    raise exc
/opt/conda/lib/python3.8/site-packages/dask/local.py:223: in execute_task
    result = _execute_task(task, data)
/opt/conda/lib/python3.8/site-packages/dask/core.py:121: in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
cs-config/cs_config/helpers.py:185: in nth_year_results
    agg1, agg2 = fuzzed(dv1, dv2, reform_affected, 'aggr')
cs-config/cs_config/helpers.py:156: in fuzzed
    group2.iloc[idx] = group1.iloc[idx]
/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py:692: in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
/opt/conda/lib/python3.8/site-packages/pandas/core/indexing.py:1635: in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pandas.core.indexing._iLocIndexer object at 0x7f8740210130>
indexer = (178095, slice(None, None, None))
value = othertaxes                  0.000000
c04600                   9586.520000
aftertax_income        105404.321656
surtax ...        2.000000
c09600                      0.000000
c04470                      0.000000
Name: 178095, dtype: float64
name = 'iloc'

    def _setitem_with_indexer_split_path(self, indexer, value, name: str):
        """
        Setitem column-wise.
        """
        # Above we only set take_split_path to True for 2D cases
        assert self.ndim == 2
    
        if not isinstance(indexer, tuple):
            indexer = _tuplify(self.ndim, indexer)
        if len(indexer) > self.ndim:
            raise IndexError("too many indices for array")
        if isinstance(indexer[0], np.ndarray) and indexer[0].ndim > 2:
            raise ValueError(r"Cannot set values with ndim > 2")
    
        if isinstance(value, ABCSeries) and name != "iloc":
            value = self._align_series(indexer, value)
    
        # Ensure we have something we can iterate over
        info_axis = indexer[1]
        ilocs = self._ensure_iterable_column_indexer(info_axis)
    
        pi = indexer[0]
        lplane_indexer = length_of_indexer(pi, self.obj.index)
        # lplane_indexer gives the expected length of obj[indexer[0]]
    
        # we need an iterable, with a ndim of at least 1
        # eg. don't pass through np.array(0)
        if is_list_like_indexer(value) and getattr(value, "ndim", 1) > 0:
    
            if isinstance(value, ABCDataFrame):
                self._setitem_with_indexer_frame_value(indexer, value, name)
    
            elif np.ndim(value) == 2:
                self._setitem_with_indexer_2d_value(indexer, value)
    
            elif len(ilocs) == 1 and lplane_indexer == len(value) and not is_scalar(pi):
                # We are setting multiple rows in a single column.
                self._setitem_single_column(ilocs[0], value, pi)
    
            elif len(ilocs) == 1 and 0 != lplane_indexer != len(value):
                # We are trying to set N values into M entries of a single
                #  column, which is invalid for N != M
                # Exclude zero-len for e.g. boolean masking that is all-false
    
                if len(value) == 1 and not is_integer(info_axis):
                    # This is a case like df.iloc[:3, [1]] = [0]
                    #  where we treat as df.iloc[:3, 1] = 0
                    return self._setitem_with_indexer((pi, info_axis[0]), value[0])
    
                raise ValueError(
                    "Must have equal len keys and value "
                    "when setting with an iterable"
                )
    
            elif lplane_indexer == 0 and len(value) == len(self.obj.index):
                # We get here in one case via .loc with a all-False mask
                pass
    
            elif len(ilocs) == len(value):
                # We are setting multiple columns in a single row.
                for loc, v in zip(ilocs, value):
                    self._setitem_single_column(loc, v, pi)
    
            elif len(ilocs) == 1 and com.is_null_slice(pi) and len(self.obj) == 0:
                # This is a setitem-with-expansion, see
                #  test_loc_setitem_empty_append_expands_rows_mixed_dtype
                # e.g. df = DataFrame(columns=["x", "y"])
                #  df["x"] = df["x"].astype(np.int64)
                #  df.loc[:, "x"] = [1, 2, 3]
                self._setitem_single_column(ilocs[0], value, pi)
    
            else:
>               raise ValueError(
                    "Must have equal len keys and value "
                    "when setting with an iterable"
                )
E               ValueError: Must have equal len keys and value when setting with an iterable

```

### PR DESCRIPTION
**Pull request by hdoupe**
Thanks for the tip @jdebacker. 

Resolves #183

### CODE REVIEW

**Comment by hdoupe** [comment]
Just tested locally and downloaded the correct puf. @andersonfrailey @jdebacker

**Comment by hdoupe** [comment]
Jupyter book failure should be fixed by this: https://github.com/PSLmodels/Tax-Brain/pull/185

**Comment by andersonfrailey** [comment]
Remaining test failures should be resolved by #181. Taxcalc changed some of the column names that we're dropped when the automated reports are created and the old names were the cause of the bug.

**Comment by hdoupe** [comment]
@andersonfrailey looks like tests are passing now. I added a command to the build files here: https://github.com/PSLmodels/Tax-Brain/pull/184/commits/5d8041350593008f2528a4a9ba376c052f5d4ac5

**Comment by andersonfrailey** [comment]
Thanks for working on this, @hdoupe! Anything else you want added before merging?

**Comment by hdoupe** [comment]
> Thanks for working on this, @hdoupe! Anything else you want added before merging?

Nope, it's ready!

**Comment by andersonfrailey** [comment]
Merge conflict popped up after merging #186. Looks like it's an easy fix, but I want to be sure. @hdoupe your changes should be the accepted ones, right?

**Comment by hdoupe** [comment]
@andersonfrailey dang sorry I just saw the message about the merge conflict. It's resolved now.

**Comment by hdoupe** [comment]
Nvmd, looks like there's an issue with the bokeh plots returned by `json_item`. I hope Bokeh didn't change that data format...checking this out now.

cc @jdebacker sounds similar to your issue with ccc

**Pull request merged**
