### PR TITLE
Refactor TBI to work with new COMP requirements

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR is meant to bring Tax-Brain's TBI output inline with COMP's new output format. Right now, the TBI returns a dictionary full of tables and tags that COMP then processes. Now it will return a dictionary with a Bokeh layout that contains all of those outputs.

cc @hdoupe

### CODE REVIEW

**Comment by hdoupe** [comment]
Looks good @andersonfrailey. I'm working on some preliminary automated testing for the inputs and outputs formats. If you're willing to be a guinea pig, we can try that out on the new outputs before you do a release.

**Comment by andersonfrailey** [comment]
@hdoupe always down to guinea pig COMP. Let me know what needs to be done on my end.

**Comment by hdoupe** [comment]
Awesome, thanks. I'll have something for you tomorrow.

**Comment by andersonfrailey** [comment]
Latest commits add a `compconfig` directory. This will replace the TBI as the interface between COMP and Tax-Brain. All of the functions in the TBI have been moved to this directory. Additionally, the functions to get the default values, validate user input, and run the model have been changed to work with the new COMP workflow. See `compconfig/compconfig/functions.py` for details.

A later commit will remove the TBI from the repository.

cc @hdoupe

**Comment by andersonfrailey** [comment]
Latest commit removes all of the TBI files. I've also updated the tests to work with Tax-Calculator 2.0.0.

**Pull request merged**
